# Generated by Django 6.1.1 on 2026-09-29 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialevent',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
    ]
