# Generated by Django 6.1.1 on 2026-09-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_meetup_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='content',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upcoming.location')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
