# Generated by Django 6.1.1 on 2026-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_remove_specialevent_time_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gmap_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
