# Generated by Django 6.1.1 on 2026-09-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('path', models.CharField(blank=True, default='', editable=False, max_length=250, null=True)),
                ('desc', models.TextField(blank=True, default='', null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('public', models.BooleanField(default=False)),
                ('last_mod', models.DateField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', editable=False, max_length=250, null=True)),
                ('parent_page', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.template')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('alias_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
        ),
    ]
