# Generated by Django 6.1.1 on 2026-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='source',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
