# Generated by Django 6.1.1 on 2026-09-25 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
