# Generated by Django 6.1.1 on 2026-09-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_template_parent_template_template_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': [models.Case(models.When(name__iexact='index', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField()), 'display_name']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': [models.Case(models.When(parent_template__isnull=True, then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField()), 'display_name']},
        ),
        migrations.AddField(
            model_name='template',
            name='display_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, default='', help_text='(optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, help_text='choose which template to extend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='source',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
