# Generated by Django 6.1.1 on 2026-09-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_page_options_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name': 'Alias', 'verbose_name_plural': 'Alia'},
        ),
    ]
