# Generated by Django 6.1.1 on 2026-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_alias_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
