# Generated by Django 6.1.1 on 2026-09-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='content',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='app',
            name='path',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
