# Generated by Django 6.1.1 on 2026-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
