# Generated by Django 6.1.1 on 2026-09-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('file', models.FileField(upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('file', models.ImageField(height_field='file_height', upload_to='tmp/', width_field='file_width')),
                ('file_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('meetup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer', to='upcoming.meetup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationLogo',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('file', models.ImageField(height_field='file_height', upload_to='tmp/', width_field='file_width')),
                ('file_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='upcoming.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('file', models.ImageField(height_field='file_height', upload_to='tmp/', width_field='file_width')),
                ('file_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
