# Generated by Django 6.1.1 on 2026-09-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('file', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('meetup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flyer', to='upcoming.meetup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('file', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
