# Generated by Django 6.1.1 on 2026-09-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.file')),
                ('file', models.FileField(upload_to='media/')),
            ],
            bases=('media.file',),
        ),
        migrations.CreateModel(
            name='PhotoClass',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.file')),
                ('file', models.ImageField(height_field='file_height', upload_to='tmp/', width_field='file_width')),
                ('file_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
            ],
            bases=('media.file',),
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('photoclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.photoclass')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer', to='upcoming.event')),
            ],
            bases=('media.photoclass',),
        ),
        migrations.CreateModel(
            name='LocationLogo',
            fields=[
                ('photoclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.photoclass')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logo', to='upcoming.location')),
            ],
            bases=('media.photoclass',),
        ),
        migrations.CreateModel(
            name='LocationRoute',
            fields=[
                ('photoclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.photoclass')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_route', to='upcoming.location')),
            ],
            bases=('media.photoclass',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.photoclass')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.album')),
            ],
            bases=('media.photoclass',),
        ),
    ]
