# Generated by Django 6.1.1 on 2026-09-28 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_locationroute'),
        ('upcoming', '0002_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlogo',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logo', to='upcoming.location'),
        ),
    ]
