# Generated by Django 6.1.1 on 2026-09-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_locationlogo_location'),
        ('upcoming', '0003_alter_meetup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFlyer',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('file', models.ImageField(height_field='file_height', upload_to='tmp/', width_field='file_width')),
                ('file_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='upcoming.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
